const loader=document.getElementById('app-loader'),typedName=document.getElementById('typed-name'),typedSubtitle=document.getElementById('typed-subtitle'),statusEl=document.getElementById('loader-status'),progressEl=document.getElementById('loader-progress'),page=document.getElementById('main-content');
const nameText='Christine Nanyombi Mubiru, CHRA';
const subtitleText='Chief Human Resources Officer · Makerere University Business School';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function typeText(el,text){el.textContent='';for(const ch of text){el.textContent+=ch;await sleep(ch===' '?24:40)}}
async function runLoader(){statusEl.textContent='Preparing executive digital profile...';progressEl.style.width='22%';await sleep(350);statusEl.textContent='Printing identity and professional record...';progressEl.style.width='44%';await typeText(typedName,nameText);progressEl.style.width='72%';await sleep(250);await typeText(typedSubtitle,subtitleText);statusEl.textContent='Finalizing premium profile experience...';progressEl.style.width='100%';await sleep(650);loader.classList.add('fade-out');page.classList.remove('hidden');revealOnScroll()}
function revealOnScroll(){const items=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});items.forEach((item,i)=>{item.style.transitionDelay=`${Math.min(i*.07,.32)}s`;observer.observe(item)})}
function buildVCard(){return ['BEGIN:VCARD','VERSION:3.0','N:Mubiru;Christine Nanyombi;;;','FN:Christine Nanyombi Mubiru, CHRA','ORG:Makerere University Business School','TITLE:Chief Human Resources Officer','TEL;TYPE=WORK,VOICE:+256700806036','TEL;TYPE=CELL,VOICE:+256700806036','EMAIL;TYPE=WORK:cnanyombi@mubs.ac.ug','URL:https://mubs.ac.ug/','ADR;TYPE=WORK:;;Nakawa;Kampala;;;Uganda','NOTE:Digital profile by AutoMinds Africa.','END:VCARD'].join('\n')}
document.getElementById('save-contact')?.addEventListener('click',()=>{const blob=new Blob([buildVCard()],{type:'text/vcard;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='christine-nanyombi-mubiru.vcf';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)});
document.getElementById('share-profile')?.addEventListener('click',async e=>{const btn=e.currentTarget,data={title:'Christine Nanyombi Mubiru, CHRA',text:'Chief Human Resources Officer — Makerere University Business School',url:location.href};if(navigator.share){try{await navigator.share(data)}catch{}}else{await navigator.clipboard.writeText(location.href);btn.textContent='Link Copied';setTimeout(()=>btn.textContent='Share',1800)}});
window.addEventListener('load',runLoader);
